/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package recrutazerobarbershop;

import recrutazerobarbershop.entities.Barbershop;

public class App {
  
    static Barbershop barbershop = new Barbershop();
    
    public static void main(String[] args) {
      barbershop.start();
    }
}
